#
# Splunk app configuration file
#

[install]
build = 2026091501
is_configured = 0

[ui]
is_visible = 1
label = Sysmon App for Splunk

[launcher]
author = MHaggis,kidcrash22
description = Sysmon dashboards, reports, and investigation searches.
version = 2.1.0-dev.1

[package]
id = sysmon-splunk-app
check_for_updates = true

[id]
name = sysmon-splunk-app
version = 2.1.0-dev.1
